title:DojoDocs
email: sannomaru@coderdojo.com


url: "https://sannomaru.github.io/docs" # the base hostname & protocol for your site, e.g. http://example.com
baseurl : /
# Build settings
layout: default
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin

permalink: /:month/:day/:minute
gist:
  noscript: false
